name: flutter_appirc
description: App IRC Flutter Client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # ios icons
  cupertino_icons: ^1.0.0

  # socket io protocol implementation for lounge
  adhara_socket_io: ^0.4.2+1

  # for lounge commands serialization & local settings serialization
  json_annotation: ^3.1.1

  # Reactive programming
  rxdart: ^0.25.0

  # file picker UI for upload
  file_picker: ^2.1.6

  # photo picker
  image_picker: ^0.6.7+22

  # upload files via post
  http: ^0.12.0+2

  # days separators in search
  grouped_list: ^3.7.1

  # non-official widget from google
  # Use ScrollablePositionedList for messages list page
  scrollable_positioned_list: ^0.1.9

  # open links in messages
  url_launcher: ^5.7.10

  # checking network connection
  connectivity: ^2.0.2

  # firebase auth
  firebase_core: ^0.5.0
  # push notifications FCM
  firebase_messaging: ^7.0.0
  # handle crashes and non-fatal errors
  firebase_crashlytics: ^0.2.1

  # handle click on irc:// links
  uni_links: ^0.4.0

  # sqlite orm to store messages in DB instead of RAM
  floor: ^0.18.0

  # required direct dependency for floor to avoid strange compile error
  sqflite: ^1.3.2+3

  # Platform aware widgets wrapper for iOS & Android
  flutter_platform_widgets: ^0.72.0

  # shared_preferences lib and rx wrapper for shared_preferences
  # used for connection/channels settings
  streaming_shared_preferences: ^1.0.2

  # send message autocomplete
  flutter_typeahead: ^2.0.0

  # video/audio player for preview render
  chewie: ^0.12.2
  chewie_audio: ^1.1.2
  # required by chewie
  video_player: ^1.0.1

  # better lint, should be in main dependencies to ignore async/await unnecessary warnings
  pedantic: ^1.9.2

  # advanced logging
  logging: ^0.11.4

  # dependency injection framework
  provider: ^4.3.3

  # Provides internationalization and localization facilities
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # run dev tools like JSON or ORM code generators
  build_runner: ^1.10.3
  # flutter pub run build_runner build --delete-conflicting-outputs

  # for socket io commands serialization
  json_serializable: ^3.5.1
  # sqlite orm
  floor_generator: ^0.18.0

#  # easy mock for tests
#  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: CourierNew
      fonts:
        - asset: assets/fonts/courier_new_regular.ttf
        - asset: assets/fonts/courier_new_bold.ttf
          weight: 700
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
